routes/web.php
Route::get('admin/members/categoryStart', 'Admin\AdminPagesController@categoryStart')->name('admin.categories.start');
Route::get('admin/members/getCategories', 'Admin\Code_CategoriesController@get_categories')->name('admin.categories.getCategories');
Route::resource('admin/members/categories', 'Admin\Code_CategoriesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Codes CRUD
Route::get('admin/members/codeStart', 'Admin\AdminPagesController@codeStart')->name('admin.codes.start');
Route::get('admin/members/getCodes', 'Admin\CodesController@get_codes')->name('admin.code.getCodes');
Route::get('admin/members/getCodesByCategoryIds', 'Admin\CodesController@getCodesByCategoryIds')->name('admin.code.getCodesByCategoryIds');
Route::resource('admin/members/codes', 'Admin\CodesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Members CRUD
Route::get('admin/members/memberStart', 'Admin\AdminPagesController@memberStart')->name('admin.members.start');
Route::resource('admin/members/members', 'Admin\MembersController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Privileges CRUD
Route::get('admin/users/privilegeStart', 'Admin\AdminPagesController@privilegeStart')->name('admin.privileges.start');
Route::resource('admin/users/privileges', 'Admin\PrivilegesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Roles CRUD
Route::get('admin/users/roleStart', 'Admin\AdminPagesController@roleStart')->name('admin.roles.start');
Route::get('admin/users/getRolesNotInMap', 'Admin\RolesController@getroles_notin_map')->name('admin.roles.getroles-notin-map');
Route::resource('admin/roles', 'Admin\RolesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Privileges and Roles Mapping
Route::get('admin/users/privileges-roles', 'Admin\AdminPagesController@privileges_roles_map')->name('admin.privileges-roles.map');
Route::resource('admin/users/p-role-map', 'Admin\Privilege_Role_MapsController', [ 'except' => [ 'create', 'edit', 'update', 'show' ], 'as' => 'admin' ] );
// Users Registration
Route::get('admin/users/users-regist', 'Admin\AdminPagesController@users_list')->name('admin.users.regist');
Route::get('admin/users/get-users', 'Admin\UsersController@getUsers')->name('admin.users.get-users');
Route::get('admin/users/getCurrentUsers', 'Admin\UsersController@getCurrentUsers')->name('admin.users.get-current-users');
Route::resource('admin/users/users', 'Admin\UsersController', [ 'except' => [ 'store', 'create', 'edit', 'show' ], 'as' => 'admin' ] );
// Log View
Route::get('admin/users/log-view', 'Admin\AdminPagesController@logView')->name('admin.log.view');
Route::get('admin/users/getLog', 'Admin\LogController@getLog')->name('admin.log.get');
// Department code Tree mapping
Route::get('admin/members/dept-tree-map', 'Admin\AdminPagesController@departmentTree')->name('admin.dept-tree.map');
Route::get('admin/members/getCodesNotInChild', 'Admin\DepartmentTreesController@getcodes_notin_child')->name('admin.department-trees.getcodes-notin-child');
Route::resource('admin/members/department-trees', 'Admin\DepartmentTreesController', [ 'except' => [ 'create', 'edit', 'update', 'show' ], 'as' => 'admin' ] );
// Family Mapping
Route::get('admin/members/family-map', 'Admin\AdminPagesController@familyTree')->name('admin.family.map');
Route::get('admin/members/getCodesNotInChildByFamily', 'Admin\FamilyTreesController@getcodes_notin_child')->name('admin.family-trees.getcodes-notin-child');
Route::resource('admin/members/family-trees', 'Admin\FamilyTreesController', [ 'except' => [ 'create', 'edit', 'update', 'show' ], 'as' => 'admin' ] );
// Members and Departments Mapping
Route::get('admin/members/member-dept-map', 'Admin\AdminPagesController@memberDeptMap')->name('admin.member-dept.map');
Route::get('admin/members/getCodesNotInChildByMDMap', 'Admin\MemDeptMapsController@getcodes_notin_child')->name('admin.member-dept-trees.getcodes-notin-child');
Route::get('admin/members/getMembersByDepartmentId', 'Admin\MemDeptMapsController@getMembersByDepartmentId')->name('admin.member-dept-trees.getmembers-department');
Route::get('admin/members/getMembersNotAssignedCell', 'Admin\MemDeptMapsController@getMembersNotAssignedCell')->name('admin.member-dept-trees.getmembers-notassigned');
Route::get('admin/members/getMembersNotAssignedDept', 'Admin\MemDeptMapsController@getMembersNotAssignedDept')->name('admin.member-dept-trees.getmembers-notbelongin_dept');
Route::resource('admin/members/member-dept-trees', 'Admin\MemDeptMapsController', [ 'except' => [ 'create', 'edit', 'show' ], 'as' => 'admin' ] );
// Contact Email
Route::post('admin/sendContactEmail', 'Admin\AdminPagesController@sendContactEmail')->name('admin.send.contactemail');
// Tests
Route::get('admin/tests/toolbarTest', 'Admin\AdminPagesController@toolbarTest')->name('admin.tests.toolbar');
Route::get('admin/tests/searchTest', 'Admin\AdminPagesController@searchTest')->name('admin.tests.search');

// Image Upload
Route::post('admin/members/photo-crop', 'Admin\AdminPagesController@photoCropPost')->name('admin.photo-crop.post');
// Cell, Department Organizer
Route::get('admin/members/cell-orginizer', 'Admin\AdminPagesController@cellOrginizer')->name('admin.cell.orginizer');
Route::get('admin/members/dept-orginizer', 'Admin\AdminPagesController@departmentOrginizer')->name('admin.dept.orginizer');
// Route for export/download tabledata to .csv, .xls or .xlsx
Route::get('admin/members/exportCategories', 'Admin\ExportsController@exportCategories')->name('admin.export.categories');
Route::get('admin/members/exportCodes', 'Admin\ExportsController@exportCodes')->name('admin.export.codes');
Route::get('admin/members/exportPrivileges', 'Admin\ExportsController@exportPrivileges')->name('admin.export.privileges');
Route::get('admin/members/exportRoles', 'Admin\ExportsController@exportRoles')->name('admin.export.roles');
Route::get('admin/members/exportUsers', 'Admin\ExportsController@exportUsers')->name('admin.export.users');
Route::get('admin/members/exportLogs', 'Admin\ExportsController@exportLogs')->name('admin.export.logs');
Route::get('admin/members/exportMembers', 'Admin\ExportsController@exportMembers')->name('admin.export.members');
Route::get('admin/members/exportPrivilegeRoleMaps', 'Admin\ExportsController@exportPrivilegeRoleMaps')->name('admin.export.privilegerolemaps');
Route::get('admin/members/exportDepartmentTrees', 'Admin\ExportsController@exportDepartmentTrees')->name('admin.export.departmenttrees');
Route::get('admin/members/exportFamilyTrees', 'Admin\ExportsController@exportFamilyTrees')->name('admin.export.familytrees');
Route::get('admin/members/exportMemDeptMaps', 'Admin\ExportsController@exportMemDeptMaps')->name('admin.export.memdeptmaps');
// Route for DB Backup and ibase_restore
// DB Backup
Route::get('admin/users/dbbackup', 'Admin\AdminPagesController@dbBackup')->name('admin.db.backup');
// DB Restore
Route::get('admin/users/dbrestore', 'Admin\AdminPagesController@dbRestore')->name('admin.db.restore');
/*
|--------------------------------------------------------------------------
| MEMBER LIST RESTFUL API
|--------------------------------------------------------------------------
*/
/**
 * Method: GET
 * URL: /okcc/memberList/categories: Retrieve search categories
 */
Route::resource('okcc/memberList/categories', 'Rest\MemberList\CategoryController')->only([
    'index'
])->middleware('auth');

/**
 * Method: GET
 * URL: /okcc/memberList/member/{id}: Retrieve all information for the given member
 *
 */
Route::resource('okcc/memberList/member', 'Rest\MemberList\MemberController')->only([
    'show'
])->middleware('auth');
/**
 * Method: GET
 * URL: /okcc/memberList/memberList: Retrieve all members
 * URL: /okcc/memberList/memberList/{code}: Retrieve members who matched the code
 *
 */
Route::resource('okcc/memberList/memberList', 'Rest\MemberList\MemberListController')->only([
    'index', 'show'
])->middleware('auth');

/**
 * Method: GET
 * URL: /okcc/memberList/search/{searchString}: Retrieve members who matched the string
 *
 */
Route::resource('okcc/memberList/search', 'Rest\MemberList\SearchController')->only([
    'show'
])->middleware('auth');

/**
 * Method: GET
 * URL: /okcc/memberList/settings: Retrieve memberList settings (landing page bookmark,
 *                                 table column info)
 *
 */
Route::get('okcc/memberList/settings', 'Rest\MemberList\MemberListController@getSettings')->middleware('auth');

/**
 * Method: GET
 * URL: /okcc/memberList/export: Export table data
 * Body : JSON
 *        filename: Save file name
 *        type : excel/pdf - We support excel only
 *        tablename: table name to export
 *        field: field name to export
 *
 */
Route::get('okcc/memberList/export', 'Rest\MemberList\ExportController@export')->middleware('auth')->name('memberlist.export');

/**
 * Method: GET/POST/PUT/DELETE
 * URL: /okcc/memberList/memberHistory:
 *
 */
Route::get('okcc/memberList/memberHistory/{memberid}', 'Rest\MemberList\MemberHistoryController@list')->middleware('auth');
Route::resource('okcc/memberList/memberHistory', 'Rest\MemberList\MemberHistoryController')->middleware('auth')->only(['store', 'update', 'destroy']);

/**
 * Method: GET/POST/PUT/DELETE
 * URL: /okcc/memberList/memberVisit:
 *
 */
Route::get('okcc/memberList/memberVisit/{memberid}', 'Rest\MemberList\MemberVisitController@list')->middleware('auth');
Route::resource('okcc/memberList/memberVisit', 'Rest\MemberList\MemberVisitController')->middleware('auth')->only(['store', 'update', 'destroy']);

/**
 * Method: GET
 * URL: /okcc/util/adduser/{id}/{password}: Add new user
 * This temporary restful api, and it will be removed later
 *
 */
Route::get('okcc/util/adduser/{id}/{password}', 'Rest\Util\UtilsController@addUser');

/**
 * Method: GET
 * URL: /admin/users/okcc/util/backupDB: Database Backup
 * This will backup the database
 *
 */

app/Http/Controllers/Admin/FamilyTreesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Exception;
use Config;

use App\Code;
use App\Family_Map;
use App\Member;
use App\Http\Services\Log\SystemLog;

class FamilyTreesController extends Controller {
    private $TABLE_NAME = "FAMILY_MAPS";

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $parent_id = $request->parent_id;
        // get all records of department_trees table with code table
        $result = Family_Map::where('member_pri_id', $parent_id)->with(['memberByChildId'])->with(['codeByRelationId'])->orderBy('id', 'ASC')->get();

        $lists = array();
        foreach ($result as $value) {
            array_push($lists, $this->reinforceTable($value));
        }

        $result = array("result" => $lists);
        return response()->json($result);
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $input = $request->all();

        // Define rules
        $rules = [
            'member_pri_id' => 'required',
            'member_sub_id' => 'required',
            'relation_id' => 'required',
        ];

        //Define messages
        $messages = [
            'member_pri_id.required' => 'The parent member field can not be blank.',
            'member_sub_id.required' => 'The child member field can not be blank.',
            'relation_id.required' => 'The relation code field can not be blank.',
        ];

        $validator = \Validator::make( $input, $rules, $messages );

        if ($validator->fails()) {
            return response()->json([ 'code' => 'validation', 'errors' => $validator->errors()->all() ], 200);
        } else {
            try {
                $result = Family_Map::create($request->all());
                SystemLog::write(Config::get('app.admin.logInsert'), $this->TABLE_NAME . ' [ID] ' . $result->id);
                return response()->json([ 'codes' => $result ], 200);
            } catch (Exception $e) {
                return response()->json([ 'code' => 'exception', 'errors' => $e->getMessage(), 'status' => $e->getCode() ], 200);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        try {
            Family_Map::find($id)->delete();
            SystemLog::write(Config::get('app.admin.logDelete'), $this->TABLE_NAME . ' [ID] ' . $id);
            return response()->json([ 'message' => 'DELETED!' ], 200);
        } catch (Exception $e) {
            return response()->json([ 'code' => 'exception', 'errors' => $e->getMessage(), 'status' => $e->getCode() ], 200);
        }
    }

    /**
     * get code lists except codes already registered as children of a parent in department tree.
     */
    public function getcodes_notin_child(Request $request) {
        // get code records that was already saved
        $currentLists = Family_Map::where('member_pri_id', $request->parent_id)->pluck('member_sub_id')->all();
        // add parent id in exception list
        array_push($currentLists, $request->parent_id);
        $members = Member::whereNotIn('id', $currentLists)->orderBy('first_name', 'ASC')->orderBy('last_name', 'ASC')->get();
        return response()->json(array("members" => json_decode(json_encode($members), true)));
    }

    /**
     * Return reinforced table after adding elements and the name converted by code
     */
    private function reinforceTable($v) {
        $temp['id'] = $v->id;
        $temp['child_id'] = $v->memberByChildId->id;
        if (!trim($v->memberByChildId->first_name) && !trim($v->memberByChildId->last_name)) {
            $temp['child_name'] = $v->memberByChildId->kor_name;
        } else {
            $temp['child_name'] = !trim($v->memberByChildId->first_name) ? trim($v->memberByChildId->last_name) : trim($v->memberByChildId->first_name . ' ' . trim($v->memberByChildId->last_name));
        }
        $temp['child_birth'] = $v->memberByChildId->dob;
        $temp['child_gender'] = $v->memberByChildId->gender;
        $temp['child_email'] = $v->memberByChildId->email;
        $temp['child_relation_id'] = $v->codeByRelationId->id;
        $temp['child_relation_name'] = $v->codeByRelationId->txt;

        return $temp;
    }
}

resources/views/admin/members/includes/family-tree/add.blade.php
<div class="modal fade" id="add-item" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.add', ['name' => 'Relation']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #e0e0e0;">
                <form id="addForm" class="px-3" action="{{ route('admin.family-trees.store') }}" method="post">
                    @csrf
                    {{-- Member  --}}
                    <div class="form-group row">
                        <label for="members" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.member_name') }}</label>
                        <div class="col-sm-9">
                            <select id="addMemberCombo" class="form-control" name="members" data-placeholder="{{ __('messages.adm_table.select_member') }}">

                            </select>
                        </div>
                    </div>
                    {{-- Relation  --}}
                    <div class="form-group row">
                        <label for="relations" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.relation_name') }}</label>
                        <div class="col-sm-9">
                            <select id="addRelationCombo" class="form-control" name="relations" data-placeholder="{{ __('messages.adm_table.select_relation') }}">

                            </select>
                        </div>
                    </div>
                    {{-- Buttons --}}
                    <div class="form-group text-right">
                        <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                        <button type="submit" class="btn crud-submit btn-info"><span class="fa fa-check mr-1"></span>{{ __('messages.adm_table.save_btn') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/family-tree/delete.blade.php
<div class="modal draggable fade" id="delete-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.delete', ['name' => 'Relaton']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #303030; color: #ffcc00; font-size: 1.3em;">
                <div class="container col-sm-11" id="deleteBody">
                    {!! trans('messages.adm_table.confirm_mesg') !!}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                <button type="button" class="btn crud-delete btn-danger"><span class="fa fa-thumbs-o-down mr-1"></span>{{ __('messages.adm_table.delete_btn') }}</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/family-tree/deleteall.blade.php
<div class="modal fade" id="deleteall-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.delete', ['name' => 'All Relaton']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #303030; color: #ffcc00; font-size: 1.3em;">
                <div class="container col-sm-11" id="deleteBody">
                    {!! trans('messages.adm_table.confirm_mesg') !!}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                <button type="button" class="btn crud-all btn-danger"><span class="fa fa-thumbs-o-down mr-1"></span>{{ __('messages.adm_table.delete_btn') }}</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/family-tree/show.blade.php
<div class="modal fade" id="show-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.show', ['name' => 'Relation']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #e0e0e0;">
                <div class="container col-sm-11" id="showBody">
                    <div class="row py-2">
                        <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.parent_member') }}</div>
                        <div class="col-sm-9 rounded bg-light py-2"><span class="align-middle" name="parent_txt"></span></div>
                    </div>
                    <div class="row py-2">
                        <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.child_member') }}</div>
                        <div class="col-sm-9 rounded bg-light py-2"><span class="align-middle" name="child_txt"></span></div>
                    </div>
                    <div class="row py-2">
                        <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.relation_name') }}</div>
                        <div class="col-sm-9 rounded bg-light py-2"><span class="align-middle" name="relation"></span></div>
                    </div>
                    <div class="row py-3">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-9 text-right pr-0"><button type="button" class="btn btn-secondary" data-dismiss="modal">
                            <span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.close_btn') }}</button></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>