routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// Pre-Registration Routes...
Route::get('preregister', 'Auth\PreRegisterController@showRegistrationForm')->name('preregister');
Route::post('preregister', 'Auth\PreRegisterController@sendMail')->name('preregister');
// Change password Route
Route::get('/changePassword', 'Auth\ChangePasswordController@showChangePasswordForm')->name('changePasswordForm');
Route::post('/changePassword','Auth\ChangePasswordController@changePassword')->name('changePassword');

Route::get('/', 'MainController@index')->middleware('auth');
// memberList Landing page
Route::get('/memberList', 'MainController@memberList')->middleware('auth')->name('memberList');
Route::get('menu', 'MenuController@getMenu')->name('getmenu');

/*
|--------------------------------------------------------------------------
| Admin Web Routes
|--------------------------------------------------------------------------
*/
Route::get('admin', 'Admin\AdminPagesController@index')->name('admin'); // Index page
Route::get('admin/users', 'Admin\AdminPagesController@users')->name('admin.users'); // Users landing page
Route::get('admin/members', 'Admin\AdminPagesController@members')->name('admin.members'); // Members landing page
Route::get('admin/finances', 'Admin\AdminPagesController@finances')->name('admin.finances'); // Finances landing page
Route::get('admin/inventories', 'Admin\AdminPagesController@inventories')->name('admin.inventories'); // Inventories landing page
Route::get('admin/tests', 'Admin\AdminPagesController@tests')->name('admin.tests'); // Inventories landing page


/*
|--------------------------------------------------------------------------
| Admin Subpages' Routes
|--------------------------------------------------------------------------
*/
// Categories CRUD
Route::get('admin/members/categoryStart', 'Admin\AdminPagesController@categoryStart')->name('admin.categories.start');
Route::get('admin/members/getCategories', 'Admin\Code_CategoriesController@get_categories')->name('admin.categories.getCategories');
Route::resource('admin/members/categories', 'Admin\Code_CategoriesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Codes CRUD
Route::get('admin/members/codeStart', 'Admin\AdminPagesController@codeStart')->name('admin.codes.start');
Route::get('admin/members/getCodes', 'Admin\CodesController@get_codes')->name('admin.code.getCodes');
Route::get('admin/members/getCodesByCategoryIds', 'Admin\CodesController@getCodesByCategoryIds')->name('admin.code.getCodesByCategoryIds');
Route::resource('admin/members/codes', 'Admin\CodesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Members CRUD
Route::get('admin/members/memberStart', 'Admin\AdminPagesController@memberStart')->name('admin.members.start');
Route::resource('admin/members/members', 'Admin\MembersController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Privileges CRUD
Route::get('admin/users/privilegeStart', 'Admin\AdminPagesController@privilegeStart')->name('admin.privileges.start');
Route::resource('admin/users/privileges', 'Admin\PrivilegesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Roles CRUD
Route::get('admin/users/roleStart', 'Admin\AdminPagesController@roleStart')->name('admin.roles.start');
Route::get('admin/users/getRolesNotInMap', 'Admin\RolesController@getroles_notin_map')->name('admin.roles.getroles-notin-map');
Route::resource('admin/roles', 'Admin\RolesController', [ 'except' => [ 'create', 'show', 'edit' ], 'as' => 'admin' ] );
// Privileges and Roles Mapping
Route::get('admin/users/privileges-roles', 'Admin\AdminPagesController@privileges_roles_map')->name('admin.privileges-roles.map');
Route::resource('admin/users/p-role-map', 'Admin\Privilege_Role_MapsController', [ 'except' => [ 'create', 'edit', 'update', 'show' ], 'as' => 'admin' ] );
// Users Registration
Route::get('admin/users/users-regist', 'Admin\AdminPagesController@users_list')->name('admin.users.regist');
Route::get('admin/users/get-users', 'Admin\UsersController@getUsers')->name('admin.users.get-users');
Route::get('admin/users/getCurrentUsers', 'Admin\UsersController@getCurrentUsers')->name('admin.users.get-current-users');
Route::resource('admin/users/users', 'Admin\UsersController', [ 'except' => [ 'store', 'create', 'edit', 'show' ], 'as' => 'admin' ] );
// Log View
Route::get('admin/users/log-view', 'Admin\AdminPagesController@logView')->name('admin.log.view');
Route::get('admin/users/getLog', 'Admin\LogController@getLog')->name('admin.log.get');
// Department code Tree mapping
Route::get('admin/members/dept-tree-map', 'Admin\AdminPagesController@departmentTree')->name('admin.dept-tree.map');
Route::get('admin/members/getCodesNotInChild', 'Admin\DepartmentTreesController@getcodes_notin_child')->name('admin.department-trees.getcodes-notin-child');
Route::resource('admin/members/department-trees', 'Admin\DepartmentTreesController', [ 'except' => [ 'create', 'edit', 'update', 'show' ], 'as' => 'admin' ] );
// Family Mapping
Route::get('admin/members/family-map', 'Admin\AdminPagesController@familyTree')->name('admin.family.map');
Route::get('admin/members/getCodesNotInChildByFamily', 'Admin\FamilyTreesController@getcodes_notin_child')->name('admin.family-trees.getcodes-notin-child');
Route::resource('admin/members/family-trees', 'Admin\FamilyTreesController', [ 'except' => [ 'create', 'edit', 'update', 'show' ], 'as' => 'admin' ] );
// Members and Departments Mapping
Route::get('admin/members/member-dept-map', 'Admin\AdminPagesController@memberDeptMap')->name('admin.member-dept.map');
Route::get('admin/members/getCodesNotInChildByMDMap', 'Admin\MemDeptMapsController@getcodes_notin_child')->name('admin.member-dept-trees.getcodes-notin-child');
Route::get('admin/members/getMembersByDepartmentId', 'Admin\MemDeptMapsController@getMembersByDepartmentId')->name('admin.member-dept-trees.getmembers-department');
Route::get('admin/members/getMembersNotAssignedCell', 'Admin\MemDeptMapsController@getMembersNotAssignedCell')->name('admin.member-dept-trees.getmembers-notassigned');
Route::get('admin/members/getMembersNotAssignedDept', 'Admin\MemDeptMapsController@getMembersNotAssignedDept')->name('admin.member-dept-trees.getmembers-notbelongin_dept');
Route::resource('admin/members/member-dept-trees', 'Admin\MemDeptMapsController', [ 'except' => [ 'create', 'edit', 'show' ], 'as' => 'admin' ] );
// Contact Email
Route::post('admin/sendContactEmail', 'Admin\AdminPagesController@sendContactEmail')->name('admin.send.contactemail');
// Tests
Route::get('admin/tests/toolbarTest', 'Admin\AdminPagesController@toolbarTest')->name('admin.tests.toolbar');
Route::get('admin/tests/searchTest', 'Admin\AdminPagesController@searchTest')->name('admin.tests.search');

// Image Upload
Route::post('admin/members/photo-crop', 'Admin\AdminPagesController@photoCropPost')->name('admin.photo-crop.post');
// Cell, Department Organizer
Route::get('admin/members/cell-orginizer', 'Admin\AdminPagesController@cellOrginizer')->name('admin.cell.orginizer');
Route::get('admin/members/dept-orginizer', 'Admin\AdminPagesController@departmentOrginizer')->name('admin.dept.orginizer');
// Route for export/download tabledata to .csv, .xls or .xlsx
Route::get('admin/members/exportCategories', 'Admin\ExportsController@exportCategories')->name('admin.export.categories');
Route::get('admin/members/exportCodes', 'Admin\ExportsController@exportCodes')->name('admin.export.codes');
Route::get('admin/members/exportPrivileges', 'Admin\ExportsController@exportPrivileges')->name('admin.export.privileges');
Route::get('admin/members/exportRoles', 'Admin\ExportsController@exportRoles')->name('admin.export.roles');
Route::get('admin/members/exportUsers', 'Admin\ExportsController@exportUsers')->name('admin.export.users');
Route::get('admin/members/exportLogs', 'Admin\ExportsController@exportLogs')->name('admin.export.logs');
Route::get('admin/members/exportMembers', 'Admin\ExportsController@exportMembers')->name('admin.export.members');
Route::get('admin/members/exportPrivilegeRoleMaps', 'Admin\ExportsController@exportPrivilegeRoleMaps')->name('admin.export.privilegerolemaps');
Route::get('admin/members/exportDepartmentTrees', 'Admin\ExportsController@exportDepartmentTrees')->name('admin.export.departmenttrees');
Route::get('admin/members/exportFamilyTrees', 'Admin\ExportsController@exportFamilyTrees')->name('admin.export.familytrees');
Route::get('admin/members/exportMemDeptMaps', 'Admin\ExportsController@exportMemDeptMaps')->name('admin.export.memdeptmaps');
// Route for DB Backup and ibase_restore
// DB Backup
Route::get('admin/users/dbbackup', 'Admin\AdminPagesController@dbBackup')->name('admin.db.backup');
// DB Restore
Route::get('admin/users/dbrestore', 'Admin\AdminPagesController@dbRestore')->name('admin.db.restore');
/*
|--------------------------------------------------------------------------
| MEMBER LIST RESTFUL API
|--------------------------------------------------------------------------
*/
/**
 * Method: GET
 * URL: /okcc/memberList/categories: Retrieve search categories
 */
Route::resource('okcc/memberList/categories', 'Rest\MemberList\CategoryController')->only([
    'index'
])->middleware('auth');

/**
 * Method: GET
 * URL: /okcc/memberList/member/{id}: Retrieve all information for the given member
 *
 */
Route::resource('okcc/memberList/member', 'Rest\MemberList\MemberController')->only([
    'show'
])->middleware('auth');
/**
 * Method: GET
 * URL: /okcc/memberList/memberList: Retrieve all members

app/Http/Controllers/Rest/MemberList/CategoryController.php
<?php

namespace App\Http\Controllers\Rest\MemberList;

use Illuminate\Http\Request;
use App\Http\Controllers\Rest\BaseController;
use App\Http\Services\MemberList\MemberListService;

class CategoryController extends BaseController
{
    private $memberListService;

    public function __construct() {
        $this->memberListService = new MemberListService();
    }

    /**
     * Display a listing of the search category.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->sendResponse(json_encode($this->memberListService->getCategory()),
                                   "Category retrieved successfully.");
    }
}

resources/views/admin/members/includes/categories/create.blade.php
<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.create', ['name' => 'Category']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #e0e0e0;">
                <form id="createForm" class="px-3" action="{{ route('admin.categories.store') }}" method="post">
                    @csrf
                    {{--  Category name  --}}
                    <div class="form-group row">
                        <label for="txt" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.category_name') }}</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="txt" placeholder="{{ __('messages.adm_table.category_name') }}">
                        </div>
                    </div>
                    {{--  카테고리명  --}}
                    <div class="form-group row">
                        <label for="kor_txt" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.category_kname') }}</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="kor_txt" placeholder="{{ __('messages.adm_table.category_kname') }}">
                        </div>
                    </div>
                    {{--  Enabled  --}}
                    <div class="form-group row">
                        <label for="enable" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.enable') }}</label>
                        <div class="btn-group col-sm-9">
                            <div class="form-check form-check-inline">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="radio" name="enable" id="enabled1" value="1" checked>{{ __('messages.adm_table.enable_input') }}
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="radio" name="enable" id="enabled2" value="0">{{ __('messages.adm_table.disable_input') }}
                                </label>
                            </div>
                        </div>
                    </div>
                    {{--  Field name  --}}
                    <div class="form-group row">
                        <label for="fieldName" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.field_name') }}</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="fieldName" name="fieldName" placeholder="{{ __('messages.adm_table.field_name') }}">
                        </div>
                    </div>
                    {{--  Remark  --}}
                    <div class="form-group row">
                        <label for="memo" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.memo') }}</label>
                        <div class="col-sm-9">
                            <textarea id="ckeditor-create" class="form-control" name="memo" placeholder="{{ __('messages.adm_table.memo') }}"></textarea>
                        </div>
                    </div>
                    {{-- Buttons --}}
                    <div class="form-group text-right">
                        <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                        <button type="submit" class="btn crud-submit btn-info"><span class="fa fa-check mr-1"></span>{{ __('messages.adm_table.save_btn') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/categories/delete.blade.php
<div class="modal draggable fade" id="delete-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.delete', ['name' => 'Category']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #303030; color: #ffcc00; font-size: 1.3em;">
                <div class="container col-sm-11" id="deleteBody">
                    {!! trans('messages.adm_table.confirm_mesg') !!}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                <button type="button" class="btn crud-delete btn-danger"><span class="fa fa-thumbs-o-down mr-1"></span>{{ __('messages.adm_table.delete_btn') }}</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/categories/edit.blade.php
<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.edit', ['name' => 'Category']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #e0e0e0;">
                <form id="editForm" class="px-3" action='' method="PUT">
                    @csrf
                    {{--  Category name  --}}
                    <div class="form-group row">
                        <label for="txt" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.category_name') }}</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="txt" placeholder="{{ __('messages.adm_table.category_name') }}">
                        </div>
                    </div>
                    {{--  카테고리명  --}}
                    <div class="form-group row">
                        <label for="kor_txt" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.category_kname') }}</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="kor_txt" placeholder="{{ __('messages.adm_table.category_kname') }}">
                        </div>
                    </div>
                    {{--  order: hidden  --}}
                    <div class="form-group row" style="display: none">
                        <label for="order" class="col-sm-3 col-form-label text-right">Diaplay Order</label>
                        <div class="col-sm-9">
                            <input type="number" class="form-control" name="order" placeholder='Diaplay Order'>
                        </div>
                    </div>
                    {{--  Enabled  --}}
                    <div class="form-group row">
                        <label for="enable" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.enable') }}</label>
                        <div class="btn-group col-sm-9">
                            <div class="form-check form-check-inline">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="radio" name="enable" id="enabled1" value="1" checked>{{ __('messages.adm_table.enable_input') }}
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="radio" name="enable" id="enabled2" value="0">{{ __('messages.adm_table.disable_input') }}
                                </label>
                            </div>
                        </div>
                    </div>
                    {{--  Field name  --}}
                    <div class="form-group row">
                        <label for="fieldName" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.field_name') }}</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="fieldName" name="fieldName" placeholder="{{ __('messages.adm_table.field_name') }}">
                        </div>
                    </div>
                    {{--  Remark  --}}
                    <div class="form-group row">
                        <label for="memo" class="col-sm-3 col-form-label text-right">{{ __('messages.adm_table.memo') }}</label>
                        <div class="col-sm-9">
                            <textarea id="ckeditor-edit" class="form-control" name="memo" placeholder="{{ __('messages.adm_table.memo') }}"></textarea>
                        </div>
                    </div>
                    {{-- Buttons --}}
                    <div class="form-group text-right">
                        <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                        <button type="submit" class="btn crud-update btn-info"><span class="fa fa-check mr-1"></span>{{ __('messages.adm_table.save_btn') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/categories/get-categories-for-order.blade.php
<script type="text/javascript">
    $.ajax({
        dataType: 'json',
        url: "{!! route('admin.categories.index') !!}",
        success: function(data) { // What to do if we succeed
            maxOrder = data['max_order'];
            categories = data['categories'];
            var html = '';

            for (var i=0; i < categories.length; i++) {
                html +=
                    '<tr id="' + (i+1) + '">' +
                        '<td class="order">' + (i+1) + '</td>' +
                        '<td class="txt text-left">' + categories[i]['txt'] + '</td>' +
                    '</tr>';
            }
            $("#workTbody").append(html);
        }
    });
</script>

resources/views/admin/members/includes/categories/order.blade.php
<div class="modal fade" id="make-order" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.order') }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #e0e0e0;">
                <div class="container text-center">
                    <table id='workTable' class="table table-dark table-bordered table-striped table-sm s1-font-size">
                        <thead>
                            <tr>
                                <th width="80px">{{ __('messages.adm_table.order') }}</th>
                                <th>{{ __('messages.adm_table.category_name') }}</th>
                            </tr>
                        </thead>
                        <tbody id="workTbody">
                            {{-- will be put Dynamic Row in --}}
                        </tbody>
                    </table>
                </div>
                {{-- Buttons --}}
                <div class="form-group text-right">
                    <button type="button" class="btn btn-secondary mr-2" data-dismiss="modal"><span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.cancel_btn') }}</button>
                    <button type="submit" class="btn make-order btn-info mr-3"><span class="fa fa-check mr-1"></span>{{ __('messages.adm_table.save_btn') }}</button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/members/includes/categories/show.blade.php
<div class="modal fade" id="show-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalLabel">
                <label class="modal-title h6-font-size" style="font-weight: 600">{{ __('messages.adm_title.show', ['name' => 'Category']) }}</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="background-color: #e0e0e0;">
                <div class="container col-sm-11" id="showBody">
                        <div class="row py-2">
                            <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.category_name') }}</div>
                            <div class="col-sm-9 rounded bg-light py-2"><span class="align-middle" name="txt"></span></div>
                        </div>
                        <div class="row py-2">
                            <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.enable') }}</div>
                            <div class="col-sm-9 rounded bg-light py-2"><span class="align-middle" name="enable"></span></div>
                        </div>
                        <div class="row py-2">
                            <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.field_name') }}</div>
                            <div class="col-sm-9 rounded bg-light py-2"><span class="align-middle" name="fieldName"></span></div>
                        </div>
                        <div class="row py-2">
                            <div class="col-sm-3 text-right py-2">{{ __('messages.adm_table.memo') }}</div>
                            <div class="col-sm-9 rounded bg-light py-2" style="height: 200px;"><span class="align-middle" name="memo"></span></div>
                        </div>
                    <div class="row py-3">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-9 text-right pr-0"><button type="button" class="btn btn-secondary" data-dismiss="modal">
                            <span class="fa fa-times mr-1"></span>{{ __('messages.adm_table.close_btn') }}</button></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>